### ISSUE TITLE
Improve coverage

### ISSUE THREAD

**Issue by IceBen4444** [IET-Homework-Team/neo4j-drivers#2]

**Comment by IceBen4444** [comment]
reactive-driver-impl improvement begun

**Comment by IceBen4444** [comment]
reactive-driver-impl mostly finished, typeSystem wasn't covered for an unknown reason, proceeding to other blocks.

**Comment by IceBen4444** [comment]
Coverage at 96%, issue closed.

**Comment by s55s** [comment]
Tests were reviewed by each other.
